# Final project NLP

## Text similarity using scientific papers

## Proposed project pipeline

1. Get automatically text from PDF
	
2. Tokenization
3. Text Cleaning
4. Vectorization
5. Feature engineering step
6. Algorithms 
    - AI algorithms
    - Similarities
7. Represent results
8. Interpret results


In [1]:
#!pip install pdfplumber

In [75]:
import utils as u
from importlib import reload
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import gutenberg
from datetime import datetime

import re

import matplotlib.pyplot as plt

pd.options.display.max_colwidth = 200
%matplotlib inline

In [51]:
u=reload(u)

In [55]:
text1 = u.get_text_from_pdf('../references/ref1.pdf')
text2 = u.get_text_from_pdf('../references/ref2.pdf')
text3 = u.get_text_from_pdf('../references/ref11.pdf')

#text2 = u.get_text_from_pdf('../references/book_Text_analytics.pdf')

In [ ]:
corpus = np.array(corpus)
corpus_df = pd.DataFrame({'Document': corpus, 
                          'Category': labels})
corpus_df = corpus_df[['Document', 'Category']]
corpus_df

In [58]:
corpus = np.array([text1,text2,text3])


In [67]:
corpus_df = pd.DataFrame({'Document': corpus})


In [163]:
u = reload(u)

TypeError: load() got an unexpected keyword argument 'tag'

In [83]:
c = u.corpus_to_df([text1,text2,text3])


(3, 1)

In [68]:
corpus_df

Document
0  2019 IEEE/ACM 41st International Conference on...
1  Comparative analysis of the government plans o...
2  J.Inst.Eng.IndiaSer.B\nhttps://doi.org/10.1007...

In [84]:
u=reload(u)

In [170]:
start_time = datetime.now()
norm_corpus = u.normalize_corpus(corpus)
print(norm_corpus)
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

['ieeeacm st international conference software engineering icse ieeeacm st international conference software engineering icse guiding deep learning system testing using surprise adequacy jinhan kim robert feldt shin yoo school computing dept computer science engineering dept software engineering kaist chalmers university blekinge inst technology daejeon republic korea gothenburg sweden karlskrona sweden jinhankim shin yoo kaist ac kr robert feldt chalmers se robert feldt bth se abstractdeep learning dl system rapidly anothervehicletoyieldinoneoftherarercircumstances adopted safety security critical domain urgently calling crashed vehicle expectation proved way test correctness robustness testing incorrect [ ] urgent need verify validate dl system ha traditionally relied manual collection behaviour dl system however significant part labelling data recently number coverage criterion based neuron activation value proposed criterion existing software testing technique directly applicable e

In [173]:
norm_corpus2 = u.preprocess_corpus(norm_corpus)

In [171]:

# insert spaces between special characters to isolate them    
special_char_pattern = re.compile(r'([{.(-)!}])')
doc = special_char_pattern.sub(" \\1 ", text1)
doc = remove_special_characters(doc, remove_digits=remove_digits)

NameError: name 'remove_special_characters' is not defined

In [86]:

start_time = datetime.now()
norm_corpus = u.preprocess_corpus(corpus)
print(norm_corpus)
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

['ieeeacm st international conference software engineering icse ieeeacm st international conference software engineering icse guiding deep learning system testing using surprise adequacy jinhan kim robert feldt shin yoo school computing dept computer science engineering dept software engineering kaist chalmers university blekinge inst technology daejeon republic korea gothenburg sweden karlskrona sweden jinhankimshinyookaistackr robertfeldtchalmersse robertfeldtbthse abstractdeep learning dl systems rapidly anothervehicletoyieldinoneoftherarercircumstancesand adopted safety security critical domains urgently calling crashed vehicle expectation proved ways test correctness robustness testing incorrect urgent need verify validate dl systems traditionally relied manual collection behaviours dl systems however signicant part labelling data recently number coverage criteria based neuron activation values proposed criteria existing software testing technique directly applicable essentiallyco

In [87]:
from sklearn.feature_extraction.text import CountVectorizer
# get bag of words features in sparse format
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(norm_corpus)
cv_matrix

<3x3727 sparse matrix of type '<class 'numpy.int64'>'
	with 4272 stored elements in Compressed Sparse Row format>

In [174]:
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(norm_corpus2)
cv_matrix

<3x3053 sparse matrix of type '<class 'numpy.int64'>'
	with 3534 stored elements in Compressed Sparse Row format>

In [175]:
# view dense representation 
# warning might give a memory error if data is too big
cv_matrix = cv_matrix.toarray()
cv_matrix

array([[0, 2, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 2, ..., 0, 0, 1]], dtype=int64)

In [176]:

# get all unique words in the corpus
vocab = cv.get_feature_names()
# show document feature vectors
pd.DataFrame(cv_matrix, columns=vocab)

aandbarebagsofwordsthatcontainnews  ab  abbc  abdelrahman  abhibhav  able  \
0                                   0   2     0            1         1     1   
1                                   0   0     0            0         0     0   
2                                   1   0     2            0         0     1   

   abs  abstract  abstractdeep  ac  ...  yuchi  yun  zhang  zhao  zhi  \
0    5         0             1   3  ...      1    0      3     2    2   
1    0         1             0   0  ...      0    1      0     0    0   
2    0         4             0   3  ...      0    0      0     0    0   

   zhihuacui  zhishuai  zhou  zone  zuva  
0          1         1     1     0     0  
1          0         0     0     1     0  
2          0         0     0     0     1  

[3 rows x 3053 columns]

In [112]:
cv_matrix

array([[24, 25,  3, ...,  7,  2,  0],
       [ 2,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  1,  1]], dtype=int64)

In [119]:
cv_matrix[:,3]

array([0, 1, 0], dtype=int64)

In [116]:
import xrange

ModuleNotFoundError: No module named 'xrange'

In [117]:
idx_OUT_columns = [0, 2]
idx_IN_columns = [i for i in range(np.shape(cv_matrix)[1]) if i not in idx_OUT_columns]
extractedData = cv_matrix[:,idx_IN_columns]

In [118]:
extractedData

array([[25,  0,  1, ...,  7,  2,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  1,  1]], dtype=int64)

In [ ]:
>>> A
array([[1, 2, 3, 4],
    [5, 6, 7, 8]])

>>> A[:,2] # returns the third columm
array([3, 7])

In [148]:
def containsNumber(value):
    if True in [char.isdigit() for char in value]:
        return True
    return False

In [150]:
containsNumber("hola3 a")
containsNumber("holaq a")

False

In [177]:
result =[vocab.index(c) for c in vocab if (c[0].isnumeric()or containsNumber(c)or len(c)>14) ]
print(len(result))
result

591


[0,
 16,
 18,
 23,
 35,
 61,
 62,
 63,
 64,
 65,
 70,
 77,
 80,
 86,
 87,
 90,
 98,
 103,
 105,
 107,
 112,
 113,
 115,
 116,
 118,
 122,
 127,
 128,
 133,
 135,
 136,
 139,
 143,
 144,
 146,
 147,
 148,
 149,
 154,
 156,
 164,
 168,
 176,
 177,
 178,
 179,
 182,
 189,
 194,
 195,
 196,
 197,
 203,
 206,
 208,
 213,
 216,
 219,
 220,
 225,
 230,
 231,
 232,
 234,
 239,
 242,
 245,
 246,
 252,
 254,
 255,
 267,
 280,
 281,
 282,
 291,
 295,
 298,
 301,
 306,
 309,
 313,
 318,
 325,
 326,
 336,
 348,
 349,
 350,
 366,
 371,
 372,
 373,
 374,
 375,
 377,
 393,
 395,
 397,
 398,
 401,
 419,
 435,
 451,
 471,
 472,
 501,
 508,
 511,
 517,
 522,
 525,
 526,
 527,
 529,
 535,
 540,
 545,
 547,
 553,
 567,
 568,
 569,
 578,
 610,
 612,
 616,
 621,
 622,
 623,
 627,
 633,
 664,
 668,
 669,
 691,
 702,
 706,
 722,
 736,
 738,
 742,
 743,
 746,
 756,
 763,
 766,
 768,
 769,
 787,
 807,
 812,
 814,
 815,
 822,
 824,
 825,
 829,
 830,
 843,
 852,
 857,
 858,
 862,
 863,
 880,
 882,
 891,
 898,
 905

In [138]:
idx_IN_columns = [i for i in range(np.shape(vocab)[0]) if i not in result]
extractedWords =  [vocab[i] for i in idx_IN_columns]
idx_IN_columns = [i for i in range(np.shape(cv_matrix)[1]) if i not in result]
extractedData = cv_matrix[:,idx_IN_columns]

In [135]:
extractedWords

'a1'

In [139]:
idx_IN_columns = [i for i in range(np.shape(cv_matrix)[1]) if i not in result]
extractedData = cv_matrix[:,idx_IN_columns]

In [141]:
print(np.shape(extractedData))
print(np.shape(extractedWords))
pd.DataFrame(extractedData, columns=extractedWords)

(3, 3289)
(3289,)


a1  a2  aandbarebagsofwordsthatcontainnews  ab11  ab22  ab2þbc2  abdel  \
0   2   2                                   0     1     1        0      1   
1   0   0                                   0     0     0        0      0   
2   0   0                                   1     0     0        1      0   

   abhibhav  able  abs  ...  findsthemetric  fine  finer  finest  finite  first  \
0         1     1    5  ...              0    3     2      1      1     6   
1         0     0    0  ...              0    0     0      0      0     1   
2         0     1    0  ...              1    0     0      0      0     1   

   fitness  five  flow  ffipffiffiffiffiffinffiiffiffiffiffiffibffiffiffi2ffiffi  
0       0    7    2                       0  
1       0    0    0                       0  
2       2    1    1                       1  

[3 rows x 3289 columns]

In [94]:
len(vocab)

## Eliminar columnas donde empieza con numeros 


3727

In [90]:
from sklearn.feature_extraction.text import TfidfTransformer

tt = TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True)
tt_matrix = tt.fit_transform(cv_matrix)

tt_matrix = tt_matrix.toarray()
vocab = cv.get_feature_names()
pd.DataFrame(np.round(tt_matrix, 2), columns=vocab)

00  000  0000  0000000005  0000110088  00010  00015  00020  00025  0003  \
0  0.08  0.1  0.01        0.00         0.0   0.00   0.00   0.00   0.00   0.0   
1  0.02  0.0  0.00        0.01         0.0   0.01   0.01   0.01   0.01   0.0   
2  0.00  0.0  0.00        0.00         0.0   0.00   0.00   0.00   0.00   0.0   

   ...  findsthemetric   fine  finer  finest  finite  first  fitness   five   flow  \
0  ...           0.00  0.01  0.01    0.0    0.0  0.01    0.00  0.02  0.01   
1  ...           0.00  0.00  0.00    0.0    0.0  0.01    0.00  0.00  0.00   
2  ...           0.01  0.00  0.00    0.0    0.0  0.00    0.01  0.00  0.00   

   ffipffiffiffiffiffinffiiffiffiffiffiffibffiffiffi2ffiffi  
0                    0.00  
1                    0.00  
2                    0.01  

[3 rows x 3727 columns]

In [178]:
# 
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(min_df=0., max_df=1., norm='l2',
                     use_idf=True, smooth_idf=True)
tv_matrix = tv.fit_transform(norm_corpus2)
tv_matrix = tv_matrix.toarray()

vocab = tv.get_feature_names()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)

aandbarebagsofwordsthatcontainnews    ab  abbc  abdelrahman  abhibhav  \
0                                0.00  0.01  0.00          0.0       0.0   
1                                0.00  0.00  0.00          0.0       0.0   
2                                0.01  0.00  0.01          0.0       0.0   

   able   abs  abstract  abstractdeep    ac  ...  yuchi   yun  zhang  zhao  \
0   0.0  0.02      0.00           0.0  0.01  ...    0.0  0.00   0.01  0.01   
1   0.0  0.00      0.01           0.0  0.00  ...    0.0  0.01   0.00  0.00   
2   0.0  0.00      0.02           0.0  0.01  ...    0.0  0.00   0.00  0.00   

    zhi  zhihuacui  zhishuai  zhou  zone  zuva  
0  0.01        0.0       0.0   0.0  0.00  0.00  
1  0.00        0.0       0.0   0.0  0.01  0.00  
2  0.00        0.0       0.0   0.0  0.00  0.01  

[3 rows x 3053 columns]

In [142]:
# Without number at beginning of the word
# 
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(min_df=0., max_df=1., norm='l2',
                     use_idf=True, smooth_idf=True)
tv_matrix = tv.fit_transform(norm_corpus)
tv_matrix = tv_matrix.toarray()

vocab = tv.get_feature_names()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)


00  000  0000  0000000005  0000110088  00010  00015  00020  00025  0003  \
0  0.08  0.1  0.01        0.00         0.0   0.00   0.00   0.00   0.00   0.0   
1  0.02  0.0  0.00        0.01         0.0   0.01   0.01   0.01   0.01   0.0   
2  0.00  0.0  0.00        0.00         0.0   0.00   0.00   0.00   0.00   0.0   

   ...  findsthemetric   fine  finer  finest  finite  first  fitness   five   flow  \
0  ...           0.00  0.01  0.01    0.0    0.0  0.01    0.00  0.02  0.01   
1  ...           0.00  0.00  0.00    0.0    0.0  0.01    0.00  0.00  0.00   
2  ...           0.01  0.00  0.00    0.0    0.0  0.00    0.01  0.00  0.00   

   ffipffiffiffiffiffinffiiffiffiffiffiffibffiffiffi2ffiffi  
0                    0.00  
1                    0.00  
2                    0.01  

[3 rows x 3727 columns]

In [179]:
idx_IN_columns = [i for i in range(np.shape(vocab)[0]) if i not in result]
extractedWords =  [vocab[i] for i in idx_IN_columns]
idx_IN_columns = [i for i in range(np.shape(cv_matrix)[1]) if i not in result]
extractedData = tv_matrix[:,idx_IN_columns]

In [180]:
pd.DataFrame(np.round(extractedData, 2), columns=extractedWords)

ab  abbc  abdelrahman  abhibhav  able   abs  abstract  abstractdeep  \
0  0.01  0.00          0.0       0.0   0.0  0.02      0.00           0.0   
1  0.00  0.00          0.0       0.0   0.0  0.00      0.01           0.0   
2  0.00  0.01          0.0       0.0   0.0  0.00      0.02           0.0   

     ac  accident  ...  yuchi   yun  zhang  zhao   zhi  zhihuacui  zhishuai  \
0  0.01       0.0  ...    0.0  0.00   0.01  0.01  0.01        0.0       0.0   
1  0.00       0.0  ...    0.0  0.01   0.00  0.00  0.00        0.0       0.0   
2  0.01       0.0  ...    0.0  0.00   0.00  0.00  0.00        0.0       0.0   

   zhou  zone  zuva  
0   0.0  0.00  0.00  
1   0.0  0.01  0.00  
2   0.0  0.00  0.01  

[3 rows x 2462 columns]

In [181]:
print(extractedData.shape)
print(len(extractedWords))

(3, 2462)
2462


In [182]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(tv_matrix)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

0         1         2
0  1.000000  0.064704  0.081611
1  0.064704  1.000000  0.084636
2  0.081611  0.084636  1.000000

In [147]:

similarity_matrix = cosine_similarity(extractedData)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

0         1         2
0  1.000000  0.058311  0.069289
1  0.058311  1.000000  0.074676
2  0.069289  0.074676  1.000000

In [154]:

similarity_matrix = cosine_similarity(extractedData)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

0         1         2
0  1.000000  0.058475  0.069273
1  0.058475  1.000000  0.074837
2  0.069273  0.074837  1.000000

In [162]:

similarity_matrix = cosine_similarity(extractedData)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

0         1         2
0  1.000000  0.058972  0.069769
1  0.058972  1.000000  0.075574
2  0.069769  0.075574  1.000000

In [ ]:
import spacy

nlp = spacy.load('en_core', tag=True, entity=True)
#text = 'My system keeps crashing his crashed yesterday, ours crashes daily'
def lemmatize_text(text):
    text = nlp(text)
    text = ' '.join([word.lemma_ if word.lemma_ != '-PRON-' else word.text for word in text])
    return text

In [ ]:
def lemmatize_text(text):
    text = nlp(text)
    text = ' '.join([word.lemma_ if word.lemma_ != '-PRON-' else word.text for word in text])
    return text

In [ ]:
# import these modules
from nltk.stem import WordNetLemmatizer
  
lemmatizer = WordNetLemmatizer()
  
print("rocks :", lemmatizer.lemmatize("rocks"))
print("corpora :", lemmatizer.lemmatize("corpora"))
  
# a denotes adjective in "pos"
print("better :", lemmatizer.lemmatize("better", pos ="a"))

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
def lem(text):

In [164]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word)))

Word                Lemma               
He                  He                  
was                 wa                  
running             running             
and                 and                 
eating              eating              
at                  at                  
same                same                
time                time                
He                  He                  
has                 ha                  
bad                 bad                 
habit               habit               
of                  of                  
swimming            swimming            
after               after               
playing             playing             
long                long                
hours               hour                
in                  in                  
the                 the                 
Sun                 Sun                 


In [167]:
import nltk
from nltk.stem import WordNetLemmatizer 

# Init the Wordnet Lemmatizer
lemmatizer = WordNetLemmatizer()
def lem(text):
    # Tokenize: Split the sentence into words
    word_list = nltk.word_tokenize(text)
    #print(word_list)
    #> ['The', 'striped', 'bats', 'are', 'hanging', 'on', 'their', 'feet', 'for', 'best']

    # Lemmatize list of words and join
    lemmatized_output = ' '.join([lemmatizer.lemmatize(w) for w in word_list])
    #print(lemmatized_output)
    return lemmatized_output

In [168]:
lem( "The striped bats are hanging on their feet for best")

'The striped bat are hanging on their foot for best'

In [ ]:
# Define the sentence to be lemmatized
sentence = "The striped bats are hanging on their feet for best"

# Tokenize: Split the sentence into words
word_list = nltk.word_tokenize(sentence)
print(word_list)
#> ['The', 'striped', 'bats', 'are', 'hanging', 'on', 'their', 'feet', 'for', 'best']

# Lemmatize list of words and join
lemmatized_output = ' '.join([lemmatizer.lemmatize(w) for w in word_list])
print(lemmatized_output)

In [169]:
u=reload(u)

# Pipeline

In [203]:
text1 = u.get_text_from_pdf('../references/ref1.pdf')
text2 = u.get_text_from_pdf('../references/ref2.pdf')
text3 = u.get_text_from_pdf('../references/ref11.pdf')

In [206]:
corpus = u.corpus_to_df([text1,text2,text3])
corpus = np.array([text1,text2,text3])

In [207]:
corpus

array(['2019 IEEE/ACM 41st International Conference on Software Engineering (ICSE)\n2019 IEEE/ACM 41st International Conference on Software Engineering (ICSE)\nGuiding Deep Learning System Testing Using\nSurprise Adequacy\nJinhan Kim∗, Robert Feldt†‡, Shin Yoo∗\n∗ † ‡\nSchool of Computing Dept. of Computer Science and Engineering Dept. of Software Engineering\nKAIST Chalmers University Blekinge Inst. of Technology\nDaejeon, Republic of Korea Gothenburg, Sweden Karlskrona, Sweden\n{jinhankim,shin.yoo}@kaist.ac.kr robert.feldt@chalmers.se robert.feldt@bth.se\nAbstract—Deep Learning (DL) systems are rapidly being anothervehicletoyieldinoneoftherarercircumstances,and\nadopted in safety and security critical domains, urgently calling crashed into the other vehicle when the expectation proved\nfor ways to test their correctness and robustness. Testing of\nincorrect [3]. There is an urgent need to verify and validate\nDL systems has traditionally relied on manual collection and\nbehaviours of

In [209]:
#norm_corpus = u.normalize_corpus(corpus)
norm_corpus = u.preprocess_corpus(corpus)

In [210]:
norm_corpus

array(['ieeeacm st international conference software engineering icse ieeeacm st international conference software engineering icse guiding deep learning system testing using surprise adequacy jinhan kim robert feldt shin yoo school computing dept computer science engineering dept software engineering kaist chalmers university blekinge inst technology daejeon republic korea gothenburg sweden karlskrona sweden jinhankimshinyookaistackr robertfeldtchalmersse robertfeldtbthse abstractdeep learning dl systems rapidly anothervehicletoyieldinoneoftherarercircumstancesand adopted safety security critical domains urgently calling crashed vehicle expectation proved ways test correctness robustness testing incorrect urgent need verify validate dl systems traditionally relied manual collection behaviours dl systems however signicant part labelling data recently number coverage criteria based neuron activation values proposed criteria existing software testing technique directly applicable essenti

In [215]:
from sklearn.feature_extraction.text import CountVectorizer
# get bag of words features in sparse format
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(norm_corpus)
cv_matrix

<3x3727 sparse matrix of type '<class 'numpy.int64'>'
	with 4272 stored elements in Compressed Sparse Row format>

In [220]:
# view dense representation 
# warning might give a memory error if data is too big
cv_matrix = cv_matrix.toarray()
cv_matrix

array([[24, 25,  3, ...,  7,  2,  0],
       [ 2,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  1,  1]], dtype=int64)

In [221]:
cv_matrix.shape

(3, 3727)

In [219]:
len(vocab)

3727

In [222]:

# get all unique words in the corpus
vocab = cv.get_feature_names()
# show document feature vectors
pd.DataFrame(cv_matrix, columns=vocab)

00  000  0000  0000000005  0000110088  00010  00015  00020  00025  0003  \
0  24   25     3           0           1      0      0      0      0     1   
1   2    0     0           1           0      1      1      1      1     0   
2   0    0     0           0           0      0      0      0      0     0   

   ...  findsthemetric  fine  finer  finest  finite  first  fitness  five  flow  \
0  ...              0    3     2      1      1     6       0    7    2   
1  ...              0    0     0      0      0     1       0    0    0   
2  ...              1    0     0      0      0     1       2    1    1   

   ffipffiffiffiffiffinffiiffiffiffiffiffibffiffiffi2ffiffi  
0                       0  
1                       0  
2                       1  

[3 rows x 3727 columns]

In [223]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(cv_matrix)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

0         1         2
0  1.000000  0.121543  0.126626
1  0.121543  1.000000  0.134751
2  0.126626  0.134751  1.000000

## Extracting pdfs